### ISSUE TITLE
函数与宏的标注

### ISSUE THREAD

**Issue by darionyaphet** [huangz1990/clojure_api_cn#46]
在学习Clojure的过程中我发现function和macro两者之间存在本质区别
我们翻译之中函数和宏都有  需要在一个地方标注一下么？

**Comment by huangz1990** [comment]
考虑到这两者在一般使用的时候是没有区别的，所以我在翻译的时候都没有标记。

不过我也认为标记了比较好。

以后在翻译的时候可以在标题加上声明，比如：

```
``+`` 函数
==================
```

```
``when-open`` 宏
==================
````

诸如此类。

**Comment by darionyaphet** [comment]
:+1:

**Comment by huangz1990** [comment]
:smile:
