### ISSUE TITLE
Clojure 片段收集

### ISSUE THREAD

**Issue by darionyaphet** [huangz1990/clojure_api_cn#48]
感觉真正使用起  Clojure 掌握的还是不熟练  需要差文档或者Google一些语法出来
或许还是因为Lisp风格和C风格本质上的一些不同吧 

我有一个想法 平时收集一些像是Clojure常用函数一样的程序片段存留下来 
给Clojure学习者一个提示  我抛砖引玉一下 例如一个求和的函数

```
(defn sum [values] (reduce + values))
```

非常感谢

**Comment by huangzworks** [comment]
这个主意不错，建议写在博客里面，可以做成一个系列。

**Comment by darionyaphet** [comment]
恩  积少成多
